HIP = "HIP"
RHIP = "RHIP"
RHIP_KNEE = "RHIP_KNEE"
RKNEE = "RKNEE"
RKNEE_ANKLE = "RKNEE_ANKLE"
RANKLE = "RANKLE"
RANKLE_FOOT = "RANKLE_FOOT"
RFOOT = "RFOOT"
LHIP = "LHIP"
LHIP_KNEE = "LHIP_KNEE"
LKNEE = "LKNEE"
LKNEE_ANKLE = "LKNEE_ANKLE"
LANKLE = "LANKLE"
LANKLE_FOOT = "LANKLE_FOOT"
LFOOT = "LFOOT"
SPINE1 = "SPINE1"
SPINE1_2 = "SPINE1_2"
SPINE2 = "SPINE2"
SPINE2_3 = "SPINE2_3"
SPINE3 = "SPINE3"
SPINE3_4 = "SPINE3_4"
SPINE4 = "SPINE4"
SPINE4_NECK = "SPINE4_NECK"
NECK = "NECK"
NOSE = "NOSE"
HEAD = "HEAD"
RSHOULDER = "RSHOULDER"
RUPPERARM = "RUPPERARM"
RSHOULDER_ELBOW = "RSHOULDER_ELBOW"
RELBOW = "RELBOW"
RELBOW_WRIST = "RELBOW_WRIST"
RWRIST = "RWRIST"
RHAND = "RHAND"
RHAND_SITE1 = "RHAND_SITE1"
RHAND_SITE2 = "RHAND_SITE2"
RHAND_SITE3 = "RHAND_SITE3"
RHAND_SITE4 = "RHAND_SITE4"
LSHOULDER = "LSHOULDER"
LUPPERARM = "LUPPERARM"
LSHOULDER_ELBOW = "LSHOULDER_ELBOW"
LELBOW = "LELBOW"
LELBOW_WRIST = "LELBOW_WRIST"
LWRIST = "LWRIST"
LHAND = "LHAND"
LHAND_SITE1 = "LHAND_SITE1"
LHAND_SITE2 = "LHAND_SITE2"
LHAND_SITE3 = "LHAND_SITE3"
LHAND_SITE4 = "LHAND_SITE4"

UNIT_METERS = "m",
UNIT_CENTIMETERS = "cm"
UNIT_MILIMETERS = "mm"

DEFAULT_PARENTS = {
    HIP: None,
    RHIP: HIP,

    RHIP_KNEE: RHIP,
    RKNEE: RHIP_KNEE,
    RKNEE_ANKLE: RKNEE,
    RANKLE: RKNEE_ANKLE,
    RANKLE_FOOT: RANKLE,
    RFOOT: RANKLE_FOOT,

    LHIP: HIP,
    LHIP_KNEE: LHIP,
    LKNEE: LHIP_KNEE,
    LKNEE_ANKLE: LKNEE,
    LANKLE: LKNEE_ANKLE,
    LANKLE_FOOT: LANKLE,
    LFOOT: LANKLE_FOOT,

    SPINE1: HIP,
    SPINE1_2: SPINE1,
    SPINE2: SPINE1_2,
    SPINE2_3: SPINE2,
    SPINE3: SPINE2_3,
    SPINE3_4: SPINE3,
    SPINE4: SPINE3_4,
    SPINE4_NECK: SPINE4,

    NECK: SPINE4_NECK,
    NOSE: NECK,
    HEAD: NOSE,

    RSHOULDER: NECK,
    RUPPERARM: RSHOULDER,
    RSHOULDER_ELBOW: RUPPERARM,
    RELBOW: RSHOULDER_ELBOW,
    RELBOW_WRIST: RELBOW,
    RWRIST: RELBOW_WRIST,
    RHAND: RWRIST,
    RHAND_SITE1: RHAND,
    RHAND_SITE2: RHAND,
    RHAND_SITE3: RHAND,
    RHAND_SITE4: RHAND,

    LSHOULDER: NECK,
    LUPPERARM: LSHOULDER,
    LSHOULDER_ELBOW: LUPPERARM,
    LELBOW: LSHOULDER_ELBOW,
    LELBOW_WRIST: LELBOW,
    LWRIST: LELBOW_WRIST,
    LHAND: LWRIST,
    LHAND_SITE1: LHAND,
    LHAND_SITE2: LHAND,
    LHAND_SITE3: LHAND,
    LHAND_SITE4: LHAND
}

DUMMY_INDICES = {
    HIP: [0, 0],
    RHIP: [-0.2, -0.1],
    RHIP_KNEE: [-0.2, -0.3],
    RKNEE: [-0.2, -0.5],
    RKNEE_ANKLE: [-0.2, -0.7],
    RANKLE: [-0.2, -0.9],
    RANKLE_FOOT: [-0.25, -0.95],
    RFOOT: [-0.28, -0.97],
    LHIP: [0.2, -0.1],
    LHIP_KNEE: [0.2, -0.3],
    LKNEE: [0.2, -0.5],
    LKNEE_ANKLE: [0.2, -0.7],
    LANKLE: [0.2, -0.9],
    LANKLE_FOOT: [0.25, -0.95],
    LFOOT: [0.28, -0.97],
    SPINE1: [0.0, 0.1],
    SPINE1_2: [0.0, 0.15],
    SPINE2: [0.0, 0.2],
    SPINE2_3: [0.0, 0.25],
    SPINE3: [0.0, 0.3],
    SPINE3_4: [0.0, 0.35],
    SPINE4: [0.0, 0.4],
    SPINE4_NECK: [0.0, 0.45],
    NECK: [0.0, 0.6],
    NOSE: [-0.05, 0.65],
    HEAD: [0.0, 0.72],
    RSHOULDER: [-0.2, 0.5],
    RUPPERARM: [-0.25, 0.45],
    RSHOULDER_ELBOW: [-0.3, 0.35],
    RELBOW: [-0.35, 0.25],
    RELBOW_WRIST: [-0.4, 0.15],
    RWRIST: [-0.43, 0.1],
    RHAND: [-0.45, 0.06],
    RHAND_SITE1: [-0.41, 0.02],
    RHAND_SITE2: [-0.44, -0.02],
    RHAND_SITE3: [-0.48, -0.02],
    RHAND_SITE4: [-0.51, 0.02],
    LSHOULDER: [0.2, 0.5],
    LUPPERARM: [0.25, 0.45],
    LSHOULDER_ELBOW: [0.3, 0.35],
    LELBOW: [0.35, 0.25],
    LELBOW_WRIST: [0.4, 0.15],
    LWRIST: [0.43, 0.1],
    LHAND: [0.45, 0.06],
    LHAND_SITE1: [0.41, 0.02],
    LHAND_SITE2: [0.44, -0.02],
    LHAND_SITE3: [0.48, -0.02],
    LHAND_SITE4: [0.51, 0.02]
}